version: '3.7'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: file-upload-mern:dev
    container_name: file-upload-mern-app
    command: npm start
    volumes:
      - .:/app
      - /usr/app/node_modules
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
    node_modules: